services:
  postgres:
    image: postgres:15
    container_name: postgres_telethon_bot
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - telethon_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  
  telethon_service_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telethon_bot
    networks:
      - telethon_service
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
    restart: always

networks:
  telethon_service:


volumes:
  postgres_data:  
    name: postgres_telethon_bot
